cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &

cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &

cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &

cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &







cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &

cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &

cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &

cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh 
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &







cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24Asimov/FullRunII//fitDiagnostics.root:fit_s &


cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24AsimovNoReg/FullRunII//fitDiagnostics.root:fit_s &






cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16preVFP/WJetsUL16preVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16preVFP/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16preVFP/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16preVFP/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16preVFP/FullRunII//fitDiagnostics.root:fit_s &


cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16postVFP/WJetsUL16postVFPUnfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16postVFP/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16postVFP/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16postVFP/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL16postVFP/FullRunII//fitDiagnostics.root:fit_s &


cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL17/WJetsUL17Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL17/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL17/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL17/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL17/FullRunII//fitDiagnostics.root:fit_s &


cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL18/WJetsUL18Unfolding; source build.sh
cd /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL18/FullRunII; source wrapper.sh
PostFitShapesFromWorkspace  -w /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL18/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL18/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /data/dust/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24-UL18/FullRunII//fitDiagnostics.root:fit_s &
