cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24/FullRunII//fitDiagnostics.root:fit_s &

cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &

cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24/FullRunII//fitDiagnostics.root:fit_s &

cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24/FullRunII//fitDiagnostics.root:fit_s &







cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &

cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingSubstructure_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &

cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &

cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL16preVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL16postVFPUnfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL17Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/WJetsUL18Unfolding; source build.sh &
cd /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII; source wrapper.sh &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16postVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL16preVFPUnfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL17Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
PostFitShapesFromWorkspace  -w /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_renamed.root --postfit --sampling --output /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//WJetsUL18Unfolding_fit_shapes.root -f /nfs/dust/cms/user/hinzmann/jetmass/JetMass/rhalph/UnfoldingParticleNet_N2Cut_18-09-24NoMatching/FullRunII//fitDiagnostics.root:fit_s &
